export const availableMovies = [
  {
    id: 1,
    title: "Black Widow",
    image: "./images/pages/movies/movie-blackwidow.jpg",
    landscapeImage: "./images/pages/home/movie-blackwidow.png",
    imagePathForMovieDetails:
      "../../images/pages/movies/movie-blackwidow-large.png",
    imagePathForPayment: "../../images/pages/movies/movie-blackwidow.jpg",
    imdbRating: 5,
    guidianceRating: "PG13",
    duration: "134",
    year: "2021",
    description: `In 1995, super soldier Alexei Shostakov and Black Widow Melina Vostokoff work as Russian undercover agents, posing as a family in Ohio with Natasha Romanoff and Yelena Belova as their daughters. They steal S.H.I.E.L.D. intel and escape to Cuba where their boss, General Dreykov, has Romanoff and Belova taken to the Red Room for training. In the following decades, Shostakov is imprisoned in Russia while Romanoff and Belova become successful, dangerous assassins. Romanoff eventually defects to S.H.I.E.L.D. after helping Clint Barton bomb Dreykov's Budapest office, which apparently kills Dreykov and his young daughter Antonia.`,
  },
  {
    id: 2,
    title: "Doctor Strange In The Multiverse of Maddness",
    image: "./images/pages/home/movie-doctorStrange.jpg",
    landscapeImage: "./images/pages/home/movie-doctorstrange.jpg",
    imagePathForMovieDetails:
      "../../images/pages/movies/movie-doctorstrange-large.png",
    imagePathForPayment: "../../images/pages/movies/movie-doctorStrange.jpg",
    imdbRating: 9,
    guidianceRating: "PG13",
    duration: "126",
    year: "2022",
    description: `America Chavez and a version of Stephen Strange are chased by a demon in the space between universes while searching for the Book of Vishanti. That Strange is killed and Chavez accidentally creates a portal that transports herself and Strange's corpse to Earth-616, where that universe's version of Strange rescues Chavez from another demon with help from the Sorcerer Supreme, Wong. Chavez explains that the beings are hunting her because she has the power to travel through the multiverse.`,
  },
  {
    id: 3,
    title: "1917",
    image: "./images/pages/movies/movie-detail-1917.jpg",
    landscapeImage: "./images/pages/movies/movie-detail-1917.jpg",
    imagePathForMovieDetails: "../../images/pages/movies/movie-detail-1917.jpg",
    imagePathForPayment: "../../images/pages/movies/movie-1917.jpg",
    imdbRating: 8,
    guidianceRating: "PG13",
    duration: "140",
    year: "2022",
    description: `1917 is a 2019 war film directed and produced by Sam Mendes, who
  co-wrote the film with Krysty Wilson-Cairns. Partially inspired by stories told to Mendes by
  his paternal grandfather Alfred about his service during World War I, the film takes
  place after the German retreat to the Hindenburg Line during Operation Alberich, and follows
  two British soldiers.`,
  },
  {
    id: 4,
    title: "Jumanji: The Next Level",
    image: "./images/pages/home/movie-jumanji.png",
    landscapeImage: "./images/pages/home/movie-jumanji.png",
    imagePathForMovieDetails:
      "../../images/pages/movies/movie-jumanji-large.png",
    imagePathForPayment: "../../images/pages/movies/movie-jumanji.jpg",
    imdbRating: 7,
    guidianceRating: "PG13",
    duration: "123",
    year: "2019",
    description: `Spencer Gilpin, Anthony "Fridge" Johnson, Martha Kaply, and Bethany Walker plan to meet up over Christmas break to discuss their first year out of school. The night before, Spencer, feeling despondent that his life isn't as glamorous as his friends', gets out Jumanji, where he had secretly rebuilt the console after its destruction in the previous film. When he is late to the meet-up, his friends visit his mother and are greeted by Spencer's grandfather, Eddie, and Eddie's estranged friend and former business partner, Milo Walker, who came for a visit. Fridge, Martha, and Bethany realize he has gone into the game and they follow Spencer. Eddie and Milo are also sucked into the game inadvertently while Bethany is left behind, forcing her to go to the other Jumanji player, Alex Vreeke, for help.`,
  },
  {
    id: 5,
    title: "John Wick",
    image: "./images/pages/home/movie-johnwick.png",
    landscapeImage: "./images/pages/home/movie-johnwick.png",
    imagePathForMovieDetails:
      "../../images/pages/movies/movie-johnwick-large.png",
    imagePathForPayment: "../../images/pages/movies/movie-johnwick.jpg",
    imdbRating: 6,
    guidianceRating: "PG13",
    duration: "131",
    year: "2019",
    description: `John Wick is making his way through Manhattan before he is labeled "excommunicado" for the unauthorized killing of High Table crime lord Santino D'Antonio on the grounds of the New York Continental Hotel, which is considered neutral ground. He sends his dog to safety with the concierge, Charon, at the very same hotel. At the New York Public Library, John retrieves a marker medallion and a rosary. He is injured in a fight with Ernest, another hitman, and seeks medical treatment from an underworld doctor, but his $14 million bounty activates before the doctor can finish, forcing John to complete the suturing himself. Upon leaving, he is quickly pursued by various gangs of assassins, all of whom he kills.`,
  },
  {
    id: 6,
    title: "Spider-Man: No Way Home",
    image: "./images/pages/movies/movie-spiderman.jpg",
    landscapeImage: "./images/pages/movies/movie-spiderman-large.png",
    imagePathForMovieDetails:
      "../../images/pages/movies/movie-spiderman-large.png",
    imagePathForPayment: "../../images/pages/movies/movie-spiderman.jpg",
    imdbRating: 4.9,
    guidianceRating: "PG13",
    duration: "148",
    year: "2021",
    description: `After Quentin Beck frames Peter Parker for his murder and reveals Parker's identity as Spider-Man, Parker, his girlfriend Michelle "MJ" Jones-Watson, best friend Ned Leeds, and aunt May are interrogated by the Department of Damage Control. Lawyer Matt Murdock gets Parker's charges dropped, but the group grapples with negative publicity. After Parker, MJ, and Ned's MIT applications are rejected, Parker goes to the New York Sanctum to ask Stephen Strange for help. Strange casts a spell that would make everyone forget Parker is Spider-Man, but it is corrupted when Parker repeatedly requests alterations to let his loved ones retain their memories. Strange contains the spell to stop it and makes Parker leave.`,
  },
  {
    id: 7,
    title: "DC: SuperPets",
    image: "./images/pages/movies/movie-superpets.jpg",
    landscapeImage: "./images/pages/movies/movie-superpets-large.png",
    imagePathForMovieDetails:
      "../../images/pages/movies/movie-superpets-large.png",
    imagePathForPayment: "../../images/pages/movies/movie-superpets.jpg",
    imdbRating: 4.8,
    guidianceRating: "PG13",
    duration: "105",
    year: "2022",
    description: `During the destruction of the planet Krypton, a Kryptonian Labrador Retriever comforts fellow infant survivor Kal-El as they head in an escape pod toward Earth. Years later, now known as the famous superheroes Krypto and Superman, they live in the city of Metropolis under their dual identities Bark and Clark Kent. Clark is a reporter and journalist at the Daily Planet, a newspaper company, and dating Lois Lane, a fellow journalist whom Krypto is jealous of. Thinking that Krypto needs a friend to distract him, Clark heads to an animal shelter to find one for him. A Boxer named Ace is trying to escape the shelter, when Krypto stops him. Later, Superman and Krypto spot their archenemy, LexCorp CEO Lex Luthor, reeling in a meteor strapped with orange kryptonite with a tractor beam, intending to gain superpowers. He is easily defeated as the two are aided by the Justice League.`,
  },
  {
    id: 8,
    title: "Deadpool 3",
    image: "./images/pages/movies/movie-deadpool.jpg",
    landscapeImage: "./images/pages/movies/movie-deadpool-large.png",
    imagePathForMovieDetails:
      "../../images/pages/movies/movie-deadpool-large.png",
    imagePathForPayment: "../../images/pages/movies/movie-deadpool.jpg",
    imdbRating: 4.7,
    guidianceRating: "M18",
    duration: "119",
    year: "2018",
    description: `After fighting organized crime as the wisecracking mercenary Deadpool for two years, Wade Wilson fails to kill one of his targets on his anniversary with his girlfriend Vanessa. That night, after the pair decides to start a family together, the target tracks Wade down and inadvertently kills Vanessa. Wade then kills him in revenge. Blaming himself for Vanessa's death, he attempts to die by suicide six weeks later by blowing himself up. Wade has a vision of her in the afterlife, but remains alive due to his healing abilities, and his body is put back together by Colossus. Wade is left with only a Skee-Ball token, an anniversary gift, as a final memento of Vanessa.`,
  },
  {
    id: 9,
    title: "Nope",
    image: "./images/pages/movies/movie-nope.jpg",
    landscapeImage: "./images/pages/movies/movie-nope-large.png",
    imagePathForMovieDetails: "../../images/pages/movies/movie-nope-large.png",
    imagePathForPayment: "../../images/pages/movies/movie-nope.jpg",
    imdbRating: 4.5,
    guidianceRating: "NC16",
    duration: "130",
    year: "2022",
    description: `In present-day Agua Dulce, ranch owner Otis Haywood Sr. trains and handles horses for film and television productions. When he is killed by a nickel through the eye that falls inexplicably from the sky, his children Otis "OJ" Haywood Jr. and Emerald "Em" Haywood inherit the ranch. OJ tries to keep the business afloat and maintain his father's legacy, while Em seeks fame and fortune in Hollywood. The Haywoods claim that the unnamed jockey in "Plate 626" from Eadweard Muybridge's Animal Locomotion series of photographs was a Bahamian man named Alistair E. Haywood, their ancestor.`,
  },
  {
    id: 10,
    title: "Moonlight",
    image: "./images/pages/movies/movie-moonlight.jpg",
    landscapeImage: "./images/pages/movies/movie-moonlight-large.png",
    imagePathForMovieDetails:
      "../../images/pages/movies/movie-moonlight-large.png",
    imagePathForPayment: "../../images/pages/movies/movie-moonlight.jpg",
    imdbRating: 4,
    guidianceRating: "NC16",
    duration: "111",
    year: "2016",
    description: `In Liberty City, Miami at the height of the crack epidemic, Afro-Cuban drug dealer Juan finds Chiron, a withdrawn child who goes by the nickname "Little," hiding from a group of bullies in a crackhouse. He lets Chiron spend the night with him and his girlfriend Teresa before returning Chiron to his mother Paula, who revokes his TV privileges as punishment for worrying her. Chiron continues to spend time with Juan, who teaches him how to swim and mentors him, telling him he can choose his own path in life.`,
  },
  {
    id: 11,
    title: "The Martian",
    image: "./images/pages/movies/movie-bringmehome.jpg",
    landscapeImage: "./images/pages/movies/movie-bringmehome-large.jpeg",
    imagePathForMovieDetails:
      "../../images/pages/movies/movie-bringmehome-large.jpeg",
    imagePathForPayment: "../../images/pages/movies/movie-bringmehome.jpg",
    imdbRating: 4.3,
    guidianceRating: "PG13",
    duration: "141",
    year: "2015",
    description: `In 2035, the crew of the Ares III mission to Mars is exploring Acidalia Planitia on Martian solar day (sol) 18 of their 31-sol expedition. A severe dust storm threatens to topple their Mars Ascent Vehicle (MAV). The mission is scrubbed, but as the crew evacuates, astronaut Mark Watney is struck by debris. The telemetry from his suit's bio-monitor is damaged and Watney is erroneously presumed dead. With the MAV (Mars Ascent Vehicle) on the verge of toppling, the remaining crew takes off for their orbiting vessel, the Hermes.`,
  },
];

export const upcomingMovies = [
  { title: "Us(R18)", img: "../../images/pages/movies/movie-us.jpg" },
  {
    title: "10 things I hate about you",
    img: "../../images/pages/movies/movie-hate.jpg",
  },
  {
    title: "Jurassic Park",
    img: "../../images/pages/movies/movie-jurassic.jpg",
  },

  {
    title: "007: No time to die",
    img: "../../images/pages/movies/movie-007.jpg",
  },
];
