use cineverse;

insert into movies values
(1, "Black Widow", "movie-blackwidow.jpg", "movie-blackwidow.png", "movie-blackwidow-large.png", "movie-blackwidow.jpg", 5, "PG13", 134, 2021, "In 1995, super soldier Alexei Shostakov and Black Widow Melina Vostokoff work as Russian undercover agents, posing as a family in Ohio with Natasha Romanoff and Yelena Belova as their daughters. They steal S.H.I.E.L.D. intel and escape to Cuba where their boss, General Dreykov, has Romanoff and Belova taken to the Red Room for training. In the following decades, Shostakov is imprisoned in Russia while Romanoff and Belova become successful, dangerous assassins. Romanoff eventually defects to S.H.I.E.L.D. after helping Clint Barton bomb Dreykov's Budapest office, which apparently kills Dreykov and his young daughter Antonia."),
(2, "Doctor Strange In The Multiverse of Maddness", "movie-doctorStrange.jpg", "movie-doctorstrange.jpg", "movie-doctorstrange-large.png", "movie-doctorStrange.jpg", 9, "PG13", 126, 2022, "America Chavez and a version of Stephen Strange are chased by a demon in the space between universes while searching for the Book of Vishanti. That Strange is killed and Chavez accidentally creates a portal that transports herself and Strange's corpse to Earth-616, where that universe's version of Strange rescues Chavez from another demon with help from the Sorcerer Supreme, Wong. Chavez explains that the beings are hunting her because she has the power to travel through the multiverse."),
(3, "1917", "movie-detail-1917.jpg", "movie-detail-1917.jpg", "movie-detail-1917.jpg", "movie-1917.jpg", 8, "PG13", 140, 2022, "1917 is a 2019 war film directed and produced by Sam Mendes, who co-wrote the film with Krysty Wilson-Cairns. Partially inspired by stories told to Mendes by his paternal grandfather Alfred about his service during World War I, the film takes place after the German retreat to the Hindenburg Line during Operation Alberich, and follows two British soldiers."),
(4, "Jumanji: The Next Level", "movie-jumanji.png", "movie-jumanji.png", "movie-jumanji-large.png", "movie-jumanji.png", 7, "PG13", 123, 2019, "Spencer Gilpin, Anthony 'Fridge' Johnson, Martha Kaply, and Bethany Walker plan to meet up over Christmas break to discuss their first year out of school. The night before, Spencer, feeling despondent that his life isn't as glamorous as his friends', gets out Jumanji, where he had secretly rebuilt the console after its destruction in the previous film. When he is late to the meet-up, his friends visit his mother and are greeted by Spencer's grandfather, Eddie, and Eddie's estranged friend and former business partner, Milo Walker, who came for a visit. Fridge, Martha, and Bethany realize he has gone into the game and they follow Spencer. Eddie and Milo are also sucked into the game inadvertently while Bethany is left behind, forcing her to go to the other Jumanji player, Alex Vreeke, for help."),
(5, "John Wick", "movie-johnwick.png", "movie-johnwick.png", "movie-johnwick-large.png", "movie-johnwick.jpg", 6, "PG13", 131, 2019, "John Wick is making his way through Manhattan before he is labeled \"excommunicado\" for the unauthorized killing of High Table crime lord Santino D'Antonio on the grounds of the New York Continental Hotel, which is considered neutral ground. He sends his dog to safety with the concierge, Charon, at the very same hotel. At the New York Public Library, John retrieves a marker medallion and a rosary. He is injured in a fight with Ernest, another hitman, and seeks medical treatment from an underworld doctor, but his $14 million bounty activates before the doctor can finish, forcing John to complete the suturing himself. Upon leaving, he is quickly pursued by various gangs of assassins, all of whom he kills."),
(6, "Spider-Man: No Way Home", "movie-spiderman.jpg", "movie-spiderman-large.png", "movie-spiderman-large.png", "movie-spiderman.jpg", 4.9, "PG13", 148, 2021, "After Quentin Beck frames Peter Parker for his murder and reveals Parker's identity as Spider-Man, Parker, his girlfriend Michelle \"MJ\" Jones-Watson, best friend Ned Leeds, and aunt May are interrogated by the Department of Damage Control. Lawyer Matt Murdock gets Parker's charges dropped, but the group grapples with negative publicity. After Parker, MJ, and Ned's MIT applications are rejected, Parker goes to the New York Sanctum to ask Stephen Strange for help. Strange casts a spell that would make everyone forget Parker is Spider-Man, but it is corrupted when Parker repeatedly requests alterations to let his loved ones retain their memories. Strange contains the spell to stop it and makes Parker leave."),
(7, "DC: SuperPets", "movie-superpets.jpg", "movie-superpets-large.png", "movie-superpets-large.png", "movie-superpets.jpg", 4.8, "PG13", 105, 2022, "During the destruction of the planet Krypton, a Kryptonian Labrador Retriever comforts fellow infant survivor Kal-El as they head in an escape pod toward Earth. Years later, now known as the famous superheroes Krypto and Superman, they live in the city of Metropolis under their dual identities Bark and Clark Kent. Clark is a reporter and journalist at the Daily Planet, a newspaper company, and dating Lois Lane, a fellow journalist whom Krypto is jealous of. Thinking that Krypto needs a friend to distract him, Clark heads to an animal shelter to find one for him. A Boxer named Ace is trying to escape the shelter, when Krypto stops him. Later, Superman and Krypto spot their archenemy, LexCorp CEO Lex Luthor, reeling in a meteor strapped with orange kryptonite with a tractor beam, intending to gain superpowers. He is easily defeated as the two are aided by the Justice League."),
(8, "Deadpool 3", "movie-deadpool.jpg", "movie-deadpool-large.png", "movie-deadpool-large.png", "movie-deadpool.jpg", 4.7, "M18", 119, 2018, "After fighting organized crime as the wisecracking mercenary Deadpool for two years, Wade Wilson fails to kill one of his targets on his anniversary with his girlfriend Vanessa. That night, after the pair decides to start a family together, the target tracks Wade down and inadvertently kills Vanessa. Wade then kills him in revenge. Blaming himself for Vanessa's death, he attempts to die by suicide six weeks later by blowing himself up. Wade has a vision of her in the afterlife, but remains alive due to his healing abilities, and his body is put back together by Colossus. Wade is left with only a Skee-Ball token, an anniversary gift, as a final memento of Vanessa."),
(9, "Nope", "movie-nope.jpg", "movie-nope-large.png", "movie-nope-large.png", "movie-nope.jpg", 4.5, "NC16", 130, 2022, "In present-day Agua Dulce, ranch owner Otis Haywood Sr. trains and handles horses for film and television productions. When he is killed by a nickel through the eye that falls inexplicably from the sky, his children Otis \"OJ\" Haywood Jr. and Emerald \"Em\" Haywood inherit the ranch. OJ tries to keep the business afloat and maintain his father's legacy, while Em seeks fame and fortune in Hollywood. The Haywoods claim that the unnamed jockey in \"Plate 626\" from Eadweard Muybridge's Animal Locomotion series of photographs was a Bahamian man named Alistair E. Haywood, their ancestor."),
(10, "Moonlight", "movie-moonlight.jpg", "movie-moonlight-large.png", "movie-moonlight-large.png", "movie-moonlight.jpg", 4, "NC16", 111, 2016, "In Liberty City, Miami at the height of the crack epidemic, Afro-Cuban drug dealer Juan finds Chiron, a withdrawn child who goes by the nickname \"Little,\" hiding from a group of bullies in a crackhouse. He lets Chiron spend the night with him and his girlfriend Teresa before returning Chiron to his mother Paula, who revokes his TV privileges as punishment for worrying her. Chiron continues to spend time with Juan, who teaches him how to swim and mentors him, telling him he can choose his own path in life."),
(11, "The Martian", "movie-bringmehome.jpg", "movie-bringmehome-large.jpeg", "movie-bringmehome-large.jpeg", "movie-bringmehome.jpg", 4.3, "PG13", 141, 2015, "In 2035, the crew of the Ares III mission to Mars is exploring Acidalia Planitia on Martian solar day (sol) 18 of their 31-sol expedition. A severe dust storm threatens to topple their Mars Ascent Vehicle (MAV). The mission is scrubbed, but as the crew evacuates, astronaut Mark Watney is struck by debris. The telemetry from his suit's bio-monitor is damaged and Watney is erroneously presumed dead. With the MAV (Mars Ascent Vehicle) on the verge of toppling, the remaining crew takes off for their orbiting vessel, the Hermes.");

insert into movieSessions values 
(NULL, 1, "Jurong", "14/10", "10:00"),
(NULL, 1, "Orchard", "14/10", "10:00"),
(NULL, 1, "Tampines", "14/10", "10:00");

insert into occupiedSeats values 
(1, "A1", 100000),
(1, "A2", 100000),
(1, "A16", 100000),
(1, "A17", 100000),
(1, "B8", 100000),
(1, "B10", 100000),
(1, "C14", 100000),
(1, "C15", 100000),
(1, "E19", 100000),
(1, "E20", 100000);

-- NEW

insert into upcomingMovies values 
(1, "Us(R18)", "movie-us.jpg", "movie-us-large.png", 3, "NC16", 116, 2022, "In 1986, a young girl named Adelaide watches a commercial for Hands Across America. At night, at the Santa Cruz Beach Boardwalk, she wanders away from her parents and enters a funhouse, where she encounters a doppelgänger of herself in the house of mirrors. Following the encounter she stops speaking and withdraws from her family. Years later, an adult Adelaide goes on vacation with her husband, Gabriel Wilson, and their children Zora and Jason. She is apprehensive about the trip, but despite her misgivings, the family meet with their friends Josh and Kitty Tyler and their twin daughters at the beach. On the way there, they witness paramedics taking away the bloody body of an old man. Jason later sees someone strangely similar to the old man, standing still with his arms outstretched and hands bloody."),
(2, "10 things I hate about you", "movie-hate.jpg","movie-10things-large.jpg",3,"PG13", 97, 1999, "Cameron James, a new student at Padua High School in the Seattle area, instantly falls in love with beautiful and popular sophomore Bianca Stratford. Geeky Michael Eckman warns him that Bianca is vapid and conceited, and that her overprotective father does not allow Bianca or her older sister, the shrewish Kat, to date. Kat, a senior, is accepted to Sarah Lawrence College in New York, but her father, Walter, wants her to stay close to home. Bianca wishes to date affluent senior Joey Donner, but Walter, an obstetrician worrisome of teenage pregnancy, will not allow his daughters to date until they graduate. Frustrated by Bianca's insistence and Kat's rebelliousness, Walter declares that Bianca may date only when Kat does, knowing that Kat's anti-social attitude makes this unlikely."),
(3, "Jurassic Park", "movie-jurassic.jpg", "movie-jurassic-large.jpg",5, "PG13", 147, 2022, "Jurassic World Dominion is a 2022 American science fiction action film directed by Colin Trevorrow, who co-wrote the screenplay with Emily Carmichael from a story by Derek Connolly and Trevorrow. The sequel to Jurassic World: Fallen Kingdom (2018), it is the third and final installment in the Jurassic World trilogy as well as the sixth installment in the Jurassic Park franchise, concluding the storyline of the original Jurassic Park trilogy. The film has an ensemble cast, including Chris Pratt, Bryce Dallas Howard, Laura Dern, Jeff Goldblum, Sam Neill, DeWanda Wise, Mamoudou Athie, BD Wong, and Omar Sy. Dern, Goldblum, and Neill reprise their roles from the Jurassic Park trilogy, appearing together for the first time since the 1993 film."),
(4, "007: No time to die", "movie-007.jpg", "movie-007-large.jpg",5, "PG13", 163, 2021, "No Time to Die is a 2021 spy film and the twenty-fifth in the James Bond series produced by Eon Productions, starring Daniel Craig in his fifth and final portrayal of fictional British MI6 agent James Bond. It was directed by Cary Joji Fukunaga from a screenplay by Neal Purvis, Robert Wade, Fukunaga and Phoebe Waller-Bridge. Léa Seydoux, Ben Whishaw, Naomie Harris, Jeffrey Wright, Christoph Waltz, Rory Kinnear and Ralph Fiennes reprise their roles from previous films, with Rami Malek, Lashana Lynch, Billy Magnussen, Ana de Armas, David Dencik and Dali Benssalah also starring. In No Time to Die, Bond has left active service with MI6 and is recruited by the CIA to find a kidnapped scientist, which leads to a showdown with a powerful adversary.");


insert into food values 
(null, "Combo Set A", 9.90, "set_1.png"),
(null, "Combo Set B", 10.90, "set_2.png" ),
(null, "Popcorn", 8.90, "popcorn.png"),
(null, "Beef Burger", 8.90, "beef_burger.png"),
(null, "Hot Dog", 7.90, "hotdog.png"),
(null, "Soft Drink", 3.50, "softdrink.png"),
(null, "Mineral Water", 2.00, "water.png"),
(null, "Hot Tea", 2.90, "hot_tea.png");

-- purchasedFood: foodid orderid quantity
insert into purchasedFood values
(1,100000,2),
(4,100000,2);

